version: "3.9"
services:
  currency_converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "17249:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_DB: converter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"